//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace şirket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class gorevlendirme
    {
        public int gorevlendirme_no { get; set; }
        public int proje_no { get; set; }
        public int personel_no { get; set; }
    
        public virtual personel personel { get; set; }
        public virtual proje proje { get; set; }
    }
}
