//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace şirket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class il
    {
        public il()
        {
            this.ilce = new HashSet<ilce>();
        }
    
        public string il_no { get; set; }
        public string il_ad { get; set; }
    
        public virtual ICollection<ilce> ilce { get; set; }
    }
}
