//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace şirket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ilce
    {
        public ilce()
        {
            this.cocuk = new HashSet<cocuk>();
            this.personel = new HashSet<personel>();
        }
    
        public int ilce_no { get; set; }
        public string ilce_ad { get; set; }
        public string il_no { get; set; }
    
        public virtual ICollection<cocuk> cocuk { get; set; }
        public virtual il il { get; set; }
        public virtual ICollection<personel> personel { get; set; }
    }
}
