//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace şirket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personel
    {
        public personel()
        {
            this.cocuk = new HashSet<cocuk>();
            this.gorevlendirme = new HashSet<gorevlendirme>();
        }
    
        public int personel_no { get; set; }
        public string ad { get; set; }
        public string soyad { get; set; }
        public string cinsiyet { get; set; }
        public System.DateTime dogum_tarihi { get; set; }
        public int dogum_yeri { get; set; }
        public System.DateTime baslama_tarihi { get; set; }
        public int birim_no { get; set; }
        public int unvan_no { get; set; }
        public byte calisma_saati { get; set; }
        public decimal maas { get; set; }
        public Nullable<decimal> prim { get; set; }
    
        public virtual birim birim { get; set; }
        public virtual ICollection<cocuk> cocuk { get; set; }
        public virtual ICollection<gorevlendirme> gorevlendirme { get; set; }
        public virtual ilce ilce { get; set; }
        public virtual unvan unvan { get; set; }
    }
}
