//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace şirket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class proje
    {
        public proje()
        {
            this.gorevlendirme = new HashSet<gorevlendirme>();
        }
    
        public int proje_no { get; set; }
        public string proje_ad { get; set; }
        public System.DateTime baslama_tarihi { get; set; }
        public System.DateTime planlanan_bitis_tarihi { get; set; }
    
        public virtual ICollection<gorevlendirme> gorevlendirme { get; set; }
    }
}
