//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace şirket.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class unvan
    {
        public unvan()
        {
            this.personel = new HashSet<personel>();
        }
    
        public int unvan_no { get; set; }
        public string unvan_ad { get; set; }
    
        public virtual ICollection<personel> personel { get; set; }
    }
}
